# Dataset: estudantes.csv (dados fictícios com nome, idade, nota, curso)

Tarefas:
1. Carregar o arquivo CSV com Pandas
2. Mostrar as primeiras 5 linhas
3. Usar info() e describe()
4. Selecionar apenas as colunas nome e
nota
5. Filtrar alunos com nota >= 7

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('estudantes.csv')

df.head() # Comando que mostra as 5 primeiras linhas

                Nome  Idade  Nota                  Curso
0  Adriano Imperador     22   7.4       Engenharia Civil
1     Beatriz Segall     19   9.1                Direito
2        Caio Castro     24   6.5               Medicina
3    Dandara Mariana     25   8.2          Administração
4      Emílio Surita     21   5.8  Ciência da Computação

In [ ]:
df.info() # Mostrando os atributos do dataset

df.describe() # Mostra como os dados estão distribuídos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    300 non-null    object
 1   Idade   300 non-null    int64
 2   Nota    300 non-null    float64
 3   Curso   300 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 9.5+ KB

            Idade        Nota
count  300.000000  300.000000
mean    28.143333    7.886333
std      5.492724    1.242656
min     17.000000    3.500000
25%     23.000000    7.175000
50%     28.000000    8.100000
75%     34.000000    8.800000
max     35.000000   10.000000

In [ ]:
desempenho = df[['Nome', 'Nota']] # Selecionando as colunas nome e nota do dataset

desempenho.head()

                Nome  Nota
0  Adriano Imperador   7.4
1     Beatriz Segall   9.1
2        Caio Castro   6.5
3    Dandara Mariana   8.2
4      Emílio Surita   5.8

In [ ]:
bom_desempenho = desempenho[desempenho['Nota'] >= 7] # Filtrando o Dataset com notas >=7

bom_desempenho.head(25)

                 Nome  Nota
0   Adriano Imperador   7.4
1      Beatriz Segall   9.1
3     Dandara Mariana   8.2
5     Fernanda Gentil   9.7
7     Heloísa Perissé   8.0
8         Ícaro Silva   7.2
10     Kadu Moliterno   8.5
11        Luísa Sonza   9.2
13        Nanda Costa   7.9
15    Paolla Oliveira   8.8
17      Rainer Cadete   9.4
18      Stênio Garcia   7.6
19        Tais Araújo   8.1
21         Vitor Kley   7.3
23      Xuxa Meneghel   8.9
24        Yara Amaral   7.0
25         Zezé Motta   9.5
27   Bruna Marquezine   8.3
29      Deborah Secco   7.7
30     Edson Celulari   9.0
32    Giovanna Ewbank   8.6
33    Humberto Carrão   7.1
35     João Guilherme   9.3
36     Klara Castanho   8.4
37       Lázaro Ramos   7.5