**Manipulação de dados com pandas**

1. Baixar um dataset com pelo menos duas tabelas
relacionadas
2. Praticar no Jupyter Nootebook ou Colab:
Fazer agrupamentos com groupby
Juntar as tabelas com merge
Identificar e tratar valores nulos

In [22]:
import pandas as pd

titanic = pd.read_csv("Titanic-Dataset.csv")

titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
# Agrupamentos com groupby
titanic.groupby('Sex')

# Quantas pessoas estão em cada gênero?
titanic.groupby('Sex').size()

Sex
female    314
male      577
dtype: int64

In [29]:
# Operações com merge
pessoa = titanic[['PassengerId', 'Name', 'Age']]
embarque = titanic[['PassengerId', 'Embarked', 'Fare', 'Survived']]
merge = pd.merge(pessoa,embarque, on='PassengerId')

print(merge.head())

   PassengerId                                               Name   Age  \
0            1                            Braund, Mr. Owen Harris  22.0
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2            3                             Heikkinen, Miss. Laina  26.0
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4            5                           Allen, Mr. William Henry  35.0

  Embarked     Fare  Survived
0        S   7.2500         0
1        C  71.2833         1
2        S   7.9250         1
3        S  53.1000         1
4        S   8.0500         0

In [25]:
# Tratar valores nulos
titanic.isnull().sum()
# Há alguns valores nulos nas colunas
# Age, Cabin e Embarked.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
# Assim, para tratar esse dataset vou fazer:
# Preencher Age com a média, pois é uma variável numérica.
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())

# Preencher Cabin com um valor padrão, indicando que
# a cabine do passageiro é desconhecida.
titanic['Cabin'] = titanic['Cabin'].fillna('Unknown')

# Preencher Embarked com a moda, pois há poucos
# valores ausentes e é uma variável categórica.
titanic['Embarked'] = titanic['Embarked'].fillna(titanic['Embarked'].mode()[0])

In [28]:
#Verificando se restam valores nulos:
titanic.isnull().sum()
# Como não há, a limpeza foi concluida.

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64