# Semana 6

1. Assitir a um tutorial de Pandas (groupby, merge, nulos)
2. Baixar um dataset com pelo menos duas tabelas relacionadas
3. Praticar no Jupyter Nootebook ou Colab:
    * Fazer agrupamentos com groupby
    * Juntar as tabelas com merge
    * Identificar e tratar valores nulos

In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sriharshabsprasad/movielens-dataset-100k-ratings")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'movielens-dataset-100k-ratings' dataset.
Path to dataset files: /kaggle/input/movielens-dataset-100k-ratings

In [9]:
import pandas as pd

df_movies = pd.read_csv(path + "/ml-latest-small/movies.csv")
df_ratings = pd.read_csv(path + "/ml-latest-small/ratings.csv")

In [10]:
display(df_movies.head())
display(df_ratings.head())

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [11]:
# Primeiro faremos o Merge dos dois datasets que interessam:
# Uniremos o dataset com os dados dos filmes, e o dataset com as notas:

df_movies_rating = pd.merge(df_movies, df_ratings, on="movieId")
df_movies_rating.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [16]:
# Agora, agruparemos as notas por filme filme e faremos uma média:

df_movies_rating.groupby(["movieId", "title"])["rating"].mean()

movieId  title
1        Toy Story (1995)                             3.920930
2        Jumanji (1995)                               3.431818
3        Grumpier Old Men (1995)                      3.259615
4        Waiting to Exhale (1995)                     2.357143
5        Father of the Bride Part II (1995)           3.071429
                                                        ...
193581   Black Butler: Book of the Atlantic (2017)    4.000000
193583   No Game No Life: Zero (2017)                 3.500000
193585   Flint (2017)                                 3.500000
193587   Bungo Stray Dogs: Dead Apple (2018)          3.500000
193609   Andrew Dice Clay: Dice Rules (1991)          4.000000
Name: rating, Length: 9724, dtype: float64

In [17]:
# Verificaremos se existem valores nulos

df_movies_rating.isnull().sum()

# Como não existem valores nulos, não há necessidade de tratamento.

movieId      0
title        0
genres       0
userId       0
rating       0
timestamp    0
dtype: int64